[package]
name = "mock_ls"
version = "0.1.0"
authors = ["Bruno Medeiros <bruno.do.medeiros@gmail.com>"]

[dependencies]
log = "0.3"
env_logger = "0.3"
rust_lsp = { version = "0.5.0" , path = "../.." }

[lib]
name = "example_ls"
path = "src/example_ls.rs"

[[bin]]
name = "dummy_lsp"
path = "src/main.rs"
test = false